### ISSUE TITLE
Описать модели БД и связи между ними с помощью SQLAlchemy

### ISSUE THREAD

**Issue by dcomrad** [Studio-Yandex-Practicum-Hackathons/culture_its_ok_1#14]
Список моделей взять из Пачки (как только я их туда кину)
Написать функцию, генерирующую асинхронные сессии

**Comment by STI-xa** [comment]
Сложность 6. Думаю на выполнение часа 4-5

**Comment by STI-xa** [comment]
Написала модели и асинк сессию, но пока не получается сделать первую миграцию, пробовала и с sqlite создать, но и так тоже не получилось, завтра еще буду разбираться, сегодня уже все, не соображаю.
