### ISSUE TITLE
Создать CI с проверкой линтерами для ветки develop

### ISSUE THREAD

**Issue by dcomrad** [Studio-Yandex-Practicum-Hackathons/culture_its_ok_1#17]
При push в ветку
Перечень проверок уточнить

**Comment by GUSICATC** [comment]
Займусь этой задачей (пока стандартные проверки pep и тд, список потом уточню поправлю)

**Comment by GUSICATC** [comment]
Почти все готово (нужно до настроить исключение .venv из проверки ) flake8  ,  нужен список проверок

**Comment by GUSICATC** [comment]
Настроил исключения flake8 все работает нужен список проверок для добавления и окончательной настройки

**Comment by dcomrad** [comment]
Давай для начала обойдёмся минимумом:

flake8
flake8-blind-except
flake8-broken-line
flake8-return
flake8-variables-names
pep8-naming
isort -с (с флагом -c выполняется только проверка, без перестановки импортов)

**Comment by GUSICATC** [comment]
ок сделаю

**Comment by dcomrad** [comment]
Поправил мелкий конфликт в файле .gitignore и слил изменения в develop.
Проверка не пройдена

```
Run poetry install
  poetry install
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/[3](https://github.com/Studio-Yandex-Practicum-Hackathons/culture_its_ok_1/actions/runs/5885132315/job/15961084494#step:7:3).11.[4](https://github.com/Studio-Yandex-Practicum-Hackathons/culture_its_ok_1/actions/runs/5885132315/job/15961084494#step:7:4)/x[6](https://github.com/Studio-Yandex-Practicum-Hackathons/culture_its_ok_1/actions/runs/5885132315/job/15961084494#step:7:6)4
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.4/x64/lib

Poetry could not find a pyproject.toml file in /home/runner/work/culture_its_ok_1/culture_its_ok_1 or its parents
Error: Process completed with exit code 1.
```

**Comment by dcomrad** [comment]
Увидел, что ты пометил задачу, как сделанную. Но скрипт падает! Посмотри, что не так. До этого момента, вернул задачу в статус InProgress
