### ISSUE TITLE
Сделать иммитацию написания сообщения ботом

### ISSUE THREAD

**Issue by dcomrad** [Studio-Yandex-Practicum-Hackathons/culture_its_ok_1#39]
Пользователь должен видеть в заголовке, что как будто бы бот сейчас пишет сообщение.
Во-первых, это будет признаком "человечности" бота, о которой просит заказчик.
Во-вторых, в связи с задержкой после выдачи контента (которая иногда будет достигать 10 и более секунд), пользователь, который решил не читать текст, может быть сбит с толку, т.к. подумает, что от него требуются какие-то действия.

Техническую возможность такого не проверял, но почти уверен, что это возможно.

**Comment by GUSICATC** [comment]
Вроде есть такая фитча
Да, это реализуется с помощью метода API [sendChatAction](https://core.telegram.org/bots/api#sendchataction). В aiogram выглядеть это будет так:

import asyncio
from aiogram.types import ChatActions

...

await bot.send_chat_action(message.chat.id, ChatActions.TYPING)
await asyncio.sleep(3)
await bot.send_message(message.chat.id, "Test message")

**Comment by GUSICATC** [comment]
Вроде есть такая фитча
Да, это реализуется с помощью метода API [sendChatAction](https://core.telegram.org/bots/api#sendchataction). В aiogram выглядеть это будет так:

import asyncio
from aiogram.types import ChatActions

...

await bot.send_chat_action(message.chat.id, ChatActions.TYPING)
await asyncio.sleep(3)
await bot.send_message(message.chat.id, "Test message")

**Comment by STI-xa** [comment]
@GUSICATC Александр, берешь себе или я возьму?

**Comment by STI-xa** [comment]
Тогда возьму, как раз на днях в одном боте заметила эту фичу и стало интересно, как это происходит ():)

**Comment by STI-xa** [comment]
По сложности, думаю, 7-6, по времени часов 5

**Comment by STI-xa** [comment]
Вроде разобралась с этой задачей, но пока не смогла запустить бота, изменения запушила в свою ветку, в файл utils.py

**Comment by dcomrad** [comment]
Готово
