### ISSUE TITLE
Добавить в бот функционал помощи пользователю, который часто пишет в ответ

### ISSUE THREAD

**Issue by dcomrad** [Studio-Yandex-Practicum-Hackathons/culture_its_ok_1#42]
Логика следующая:
Если пользователь шлёт много сообщений боту, нужно написать ему об этом и вывести справку по использованию бота.
У нас существует задержка между показами текста во время прохождения маршрута. В это время ничего не происходит и бот не реагирует на сообщения пользователя, что может смутить пользователя. Если пользователь начнёт написывать боту, нужно считать количество сообщений и после некоторого количества (придумать и обосновать это количество), нужно вывести некоторое сообщение. Текст сообщения формулировать в рамках этой задачи не нужно.

**Comment by danlaryushin** [comment]
Добавлен счетчик "спама". При повторной попытке несвоевременно отправить сообщение, бот отправит пользователю подсказку.
Счетчик обнуляется, если пользователь совершает предсказуемые действия: нажимает на кнопку, переходит на следующий этап.

**Comment by dcomrad** [comment]
готово
