### ISSUE TITLE
Подготовка проекта

### ISSUE THREAD

**Issue by dcomrad** [Studio-Yandex-Practicum-Hackathons/culture_its_ok_1#6]
Наполнить .gitignore
Создать infra/docker-compose-postgres.yaml для postgres и занести переменные окружения в .env.example/.postgres
Создать core/config.py с настройками (на базе pydantic BaseSettings) для бота, postgres, sentry (поля уточнить)

**Comment by dcomrad** [comment]
Обрати внимание. Убрал задачу создания бота. Поговорил с Виктором, он мне подсказал, что каждый сам создаёт себе бота для работы. Одного для всех использовать не получится.

**Comment by STI-xa** [comment]
У меня все готово, остались только поля для Sentry, я так понимаю нам нужно поле отвечающее за DSN?

**Comment by dcomrad** [comment]
Да. dsn достаточно. Переменная окружения будет SENTRY_DSN. Добавляй и создавай ПР. Кстати, можно пушить в уже слитую ранее ветку ещё раз и снова создавать ПР.
