### ISSUE TITLE
Подготовка проекта (логирование и мониторинг ошибок)

### ISSUE THREAD

**Issue by dcomrad** [Studio-Yandex-Practicum-Hackathons/culture_its_ok_1#7]
- Зарегистрироваться на сайте https://sentry.io/
- Создать новый проект для вашего сервиса и прислать dsn в чат
- Подключить приложение, используя SDK для вашего фреймворка (в main.py)
- Создать фабрику логеров в core/logger.py для получения преднастроенного (формат, обработчики) логера по имени
- Написать параметризованный декоратор (принимает логер), который логирует исключения + выгружает их в sentry. Будем вешать его на функции и методы, за ошибками в которых нужно следить

**Comment by SergeychUK92** [comment]
Сложность 6-7;
Время исполнения 6 часов

**Comment by SergeychUK92** [comment]
"Я думаю логгер сделать так"

import logging
import functools


def logger_factory(name):
    if name in ("debug", "d"):
        return logging.debug("")
    if name in ("info", "i"):
        return logging.info("")
    if name in ("warning", "w"):
        return logging.warning("")
    if name in ("error", "e"):
        return logging.error("")
    if name in ("critical", "c"):
        return logging.critical("")


def log_dec(logger):
    def wrap_func(func):
        @functools.wraps(func)
        def wrapper(*args, **kwargs):
            logger_factory(logger)
            return func(*args, **kwargs)

        return wrapper

    return wrap_func

**Comment by SergeychUK92** [comment]
"Это от Sentry"

```
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
sentry_sdk.init(
dsn="https://41822208eba34c448a81e091f3c84465@o4505686496706560.ingest.sentry.io/4505686506930176",
integrations=[DjangoIntegration()],
# If you wish to associate users to errors (assuming you are using
# django.contrib.auth) you may enable sending PII data.
send_default_pii=True,
# Set traces_sample_rate to 1.0 to capture 100%
# of transactions for performance monitoring.
# We recommend adjusting this value in production.
traces_sample_rate=1.0,
# To set a uniform sample rate
# Set profiles_sample_rate to 1.0 to profile 100%
# of sampled transactions.
# We recommend adjusting this value in production,
profiles_sample_rate=1.0,
)
```

**Comment by SergeychUK92** [comment]
Мне очень нужен проект для того, чтобы я мог закинуть в settings настройки от Sentry

**Comment by dcomrad** [comment]
Тебе не обязательно для этого готовый проект. Подготовкой проекта в части создания классов с настройками занимается Полина и тебе достаточно договориться с ней о формате этих настроек. Скорее всего, это будет реализовано так:

`
class SentrySettings(BaseSettings):
    dsn: str = Field(env='SENTRY_DSN')
    ...

class Settings(BaseSettings):
    sentry: SentrySettings = SentrySettings()
    ...

settings = Settings()
`

тогда у себя ты сделаешь импорт модуля с настройками и будешь использовать так: settings.sentry.dsn

обсуди это с Полиной в личке. Потом просто проследи, всё ли будет так, как договорились.

Ты уже сейчас можешь коммитить свою работу в новую ветку и кидать пул-реквест.
